#!/usr/bin/env python3
"""Fetch Unsplash images for each recipe in menu.json.

Rules:
- If a recipe exists in preferences.json with good_count > 0 and photo_url,
  reuse that URL without calling the API.
- Otherwise fetch top 3 results from Unsplash using recipe's search_keyword field.
- After fetching, if a recipe has good_count > 0, persist photo_url back to
  preferences.json so it can be reused in future weeks.
"""
import json
import os
import sys

try:
    import requests
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", "requests"])
    import requests

API_KEY = os.environ.get("UNSPLASH_ACCESS_KEY", "")
if not API_KEY:
    print("ERROR: UNSPLASH_ACCESS_KEY not set", file=sys.stderr)
    sys.exit(1)

ROOT = os.path.join(os.path.dirname(__file__), "..")
MENU_PATH = os.path.join(ROOT, "menu.json")
PREFS_PATH = os.path.join(ROOT, "preferences.json")


def fetch_unsplash(keyword: str) -> list[dict]:
    """Return up to 3 image dicts from Unsplash, or [] on failure."""
    try:
        resp = requests.get(
            "https://api.unsplash.com/search/photos",
            params={"query": keyword, "per_page": 3, "orientation": "squarish"},
            headers={"Authorization": f"Client-ID {API_KEY}"},
            timeout=10,
        )
        resp.raise_for_status()
        results = []
        for p in resp.json().get("results", []):
            results.append({
                "url": p["urls"]["regular"],
                "photographer": p["user"]["name"],
                "photographer_url": p["user"]["links"]["html"],
                "unsplash_url": p["links"]["html"],
            })
        return results
    except Exception as e:
        print(f"  WARN: API call failed for '{keyword}': {e}", file=sys.stderr)
        return []


def fetch_unsplash_with_fallback(keyword: str) -> tuple[list[dict], str]:
    """Fetch from Unsplash; if 0 results, retry with progressively shorter keyword.
    Returns (results, used_keyword).
    """
    results = fetch_unsplash(keyword)
    if results:
        return results, keyword

    # Fallback: drop words from the end one by one
    words = keyword.split()
    for n in range(len(words) - 1, 1, -1):
        shorter = " ".join(words[:n])
        print(f"  → fallback keyword: '{shorter}'")
        results = fetch_unsplash(shorter)
        if results:
            return results, shorter

    return [], keyword


def main():
    with open(MENU_PATH, encoding="utf-8") as f:
        menu = json.load(f)
    with open(PREFS_PATH, encoding="utf-8") as f:
        prefs = json.load(f)

    # Build lookup: name → saved photo info (liked recipes only)
    saved_photos = {
        r["name"]: {"url": r["photo_url"], "credit": r.get("photo_credit", {})}
        for r in prefs.get("recipes", [])
        if r.get("good_count", 0) > 0 and r.get("photo_url")
    }
    prefs_by_name = {r["name"]: r for r in prefs.get("recipes", [])}

    prefs_dirty = False

    for recipe in menu.get("main", []) + menu.get("side", []):
        name = recipe["name"]
        recipe.pop("svg", None)

        # Reuse saved photo for liked recipes
        if name in saved_photos:
            saved = saved_photos[name]
            recipe["images"] = [saved["url"]]
            recipe["image_credits"] = [saved["credit"]]
            print(f"Reusing saved photo: {name}")
            continue

        # Fetch from Pexels using search_keyword generated by LLM
        keyword = recipe.get("search_keyword") or name
        print(f"Fetching: {name} → '{keyword}'")
        results, used_keyword = fetch_unsplash_with_fallback(keyword)

        if results:
            recipe["images"] = [r["url"] for r in results]
            recipe["image_credits"] = [
                {"photographer": r["photographer"],
                 "photographer_url": r["photographer_url"],
                 "unsplash_url": r["unsplash_url"]}
                for r in results
            ]
            print(f"  ✓ {len(results)} photos fetched")

            # Persist to prefs if this recipe is liked
            if name in prefs_by_name and prefs_by_name[name].get("good_count", 0) > 0:
                prefs_by_name[name]["photo_url"] = results[0]["url"]
                prefs_by_name[name]["photo_credit"] = recipe["image_credits"][0]
                prefs_dirty = True
                print(f"  → saved to preferences (good_count > 0)")
        else:
            recipe["images"] = []
            recipe["image_credits"] = []
            print(f"  ✗ no images found")

    with open(MENU_PATH, "w", encoding="utf-8") as f:
        json.dump(menu, f, ensure_ascii=False, indent=2)
    print("\nmenu.json updated.")

    if prefs_dirty:
        with open(PREFS_PATH, "w", encoding="utf-8") as f:
            json.dump(prefs, f, ensure_ascii=False, indent=2)
        print("preferences.json updated (photo_url saved).")


if __name__ == "__main__":
    main()
